### ISSUE TITLE
TypeError: type torch.cuda.FloatTensor not available

### ISSUE THREAD

**Issue by frmunoz** [TheoreticalEcology/s-jSDM#29]
With the latest version, I have the new following error :

````
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

Detailed traceback: 
  File "C:\Program Files\R\R-3.6.2\library\sjSDM\python\sjSDM_py\model_new.py", line 171, in build
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
  File "C:\ProgramData\Anaconda3\envs\r-reticulate\lib\site-packages\torch\__init__.py", line 206, in set_default_tensor_type
    _C._set_default_tensor_type(t)
````

Does the new version require reinstalling Torch or Cuda?

**Comment by MaximilianPi** [comment]
No, cuda is not required, this error should only appear if you try to use the gpu device without having one. 
Did you set device='gpu' in sjSDM? Could you please post code to reproduce this error? 

Anyway, I set another cuda checker into the python core to overrule the device field.

**Comment by frmunoz** [comment]
I am quite confused, because I first installed the package with "gpu" option, and I could perform the model earlier today (meaning my computer could handle that).
Only with the latest version I have had the error message.

**Comment by florianhartig** [comment]
Hi Francois, while Max is helping you with your problem, I just wanted to say that we really appreciate these error messages, to optimize the install procedure (which is indeed tricky, because of all the python dependencies)

**Comment by MaximilianPi** [comment]
Hi Francois, 
I agree with Florian. Many thanks for your patience . 

> I first installed the package with "gpu" option

Yes, you can install the pytorch GPU version even if you have no NVIDIA GPU (the only difference between the cpu and gpu PyTorch version is that the cpu version comes without the cuda stuff (~500mb))

At this point, do you use a saved model or a model from a old/previous session? I changed in last commits a few global variables which might conflict with saved/old models from previous R sessions.
Are you able to run in a fresh session the sjSDM example?:

```
# Basic workflow:
## simulate community:
com = simulate_SDM(env = 3L, species = 5L, sites = 100L)

## fit model:
model = sjSDM(Y = com$response,env = com$env_weights, iter = 10L)
predict(model)
predict(model, newdata=com$env_weights)
```

**Comment by frmunoz** [comment]
I have run this example, and it works, unless I have the following warning,

`..\torch\csrc\utils\tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.`

**Comment by frmunoz** [comment]
> Hi Francois, while Max is helping you with your problem, I just wanted to say that we really appreciate these error messages, to optimize the install procedure (which is indeed tricky, because of all the python dependencies)

Hello Florian,
I am happy if my feedback can be helpful. :-)
Many thanks to Max and you for the wonderful work you have done for building this package!
I am very excited and motivated to use this.
All the best,
François

**Comment by MaximilianPi** [comment]
Hi Francois, 
weird, the warning shouldn't appear with the latest pkg version. But for now you can safely ignore this warning (which is caused by transferring the R objects to the python functions but does not influence the model fitting). 

I suggest that you rerun your analysis with the latest pkg version (re-install the sjSDM package - but there's no need to run install_sjSDM again) and let's how it goes
